### ISSUE TITLE
Assignment resources cause stack to go into UPDATE_ROLLBACK_FAILED during permission set update

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/aws-cloudformation-resource-providers-sso#22]
We're seeing failures where an update to a permission set resource triggers an update to (unchanged) assignment resources, which is expected, but these assignment resources then appear to not recognize there is no change and attempt to create a new assignment, but it is of course not a new assignment, it already exists, raising a conflict exception. The stack then goes into UPDATE_ROLLBACK_IN_PROGRESS, but during the deletion phase of these assignment resources, they error out with the opaque message "Internal error". This puts the stack in UPDATE_ROLLBACK_FAILED, and because there is no customer-side remediation, nothing can be done other than to delete the entire stack.

**Comment by andriiglukhyi** [comment]
Hey Ben thanks for opening this issue.
Could share some more data?
1) By "update to a permission set resource" you mean rename of the resource itself?
2) Do you have any examples of the template we could use to reproduce this issue?

**Comment by benkehoe** [comment]
1. No resource name changes. We have experienced this with nothing more than a change to the inline policy on the permission set.
2. Hard to provide a concrete template because the assignments have identitystore ids and account numbers. But we've experienced this with a dead simple template with a permission set and a couple of assignment resources.

We've already engaged with AWS support on this issue and been told a fix is in the works, but I wanted to provide a public tracking issue for people to know when it has been resolved.

**Comment by andriiglukhyi** [comment]
We haven't changed any handler logic for a months.

And overall CFN resource mapping is done by the CFN team, so this is definitely looks like CFN core issue. 

I'll engage with CFN to keep track on the fix, will keep you posted.

**Comment by andriiglukhyi** [comment]
We haven't changed any handler logic for a months.

And overall CFN resource mapping is done by the CFN team, so this is definitely looks like CFN core issue. 

I'll engage with CFN to keep track on the fix, will keep you posted.

**Comment by andriiglukhyi** [comment]
Hey Ben, we have deployed a few pr to mitigate issues described above.
Please let us know if you still have a problems with assignments

**Comment by hlascelles** [comment]
We are seeing issues like this as of ~6 days ago.

When we create a PermissionSet and assign it, it all works. If we then (say) remove the PermissionSet (and assignment) it is removed from the account, but not from the list of PermissionSets as a whole.

ie, adding an assigned PermissionSet, then removing it all, then adding again doesn't work.

**Comment by andriiglukhyi** [comment]
Hey Harry, thanks for bringing this up. 

Could elaborate more on "remove the PermissionSet (and assignment) it is removed from the account, but not from the list of PermissionSets as a whole." it's not that clear what is expected and current behavioral

**Comment by benkehoe** [comment]
We are seeing the same issue we saw with `::Assignment` with `::PermissionSet`, that without any values actually changing, the permission set resource can go into an update-replace cycle. In particular, we saw this when adding a `DeletionPolicy` to the resource (which, because of this issue, ironically caused CloudFormation to attempt to delete the resource).

**Comment by andriiglukhyi** [comment]
Hey Ban, I had conversation with CFN team today. They said they are mitigated this issue.
Let us know if you still experiencing anything odd.

**Comment by hlascelles** [comment]
Our example is: You have a stack that has one `AWS::SSO::PermissionSet` and also one `AWS::SSO::Assignment` that gives that PermissionSet to a group in an AWS account.

That rollout works fine.

Then, if you remove those two items and update the stack, the `AWS::SSO::Assignment` goes as expected. Also, the `AWS::SSO::PermissionSet` is removed from the list on the account page. 


ie Those two lines are removed in the two places in this image:

![image](https://user-images.githubusercontent.com/299102/111834593-ba58b580-88eb-11eb-8e45-8bef57becc2a.png)



However the PermissionSet remains here:

![image](https://user-images.githubusercontent.com/299102/111834719-e411dc80-88eb-11eb-9a0a-484dacd634ef.png)


This means when you readd those resources and try again it fails with "PermissionSet already exists". You must point-n-click delete it.

A much worse case scenario that we had (details are a bit more hazy) was that we renamed the PermissionSet with a dud Assignment. In that case the new PermissionSet is created with the new name, the old one was deleted (but not really! see above), then the Assignment failed. Then stack rolled back by deleting the new PermissionSet and tried to recreat the old one, but it couldn't because it still existed. We were stuck in `ROLLBACK_FAILED`. It was something along those lines.

**Comment by benkehoe** [comment]
I can still reliably put a stack in `UPDATE_ROLLBACK_FAILED`. Use the following template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  PermSetName:
    Type: String
  InstanceArn:
    Type: String
  AccountId:
    Type: String
  PrincipalType:
    Type: String
    Default: USER
  PrincipalId:
    Type: String
Resources:
  PermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: !Ref PermSetName
      InstanceArn: !Ref InstanceArn
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
        - Sid: DenyAll
          Effect: Deny
          Action: "*"
          Resource: "*"

  Assignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref InstanceArn
      PrincipalType: !Ref PrincipalType
      PrincipalId: !Ref PrincipalId
      PermissionSetArn: !GetAtt PermissionSet.PermissionSetArn
      TargetType: AWS_ACCOUNT
      TargetId: !Ref AccountId
```

Create the stack.
Update the stack, changing the `PermSetName` parameter. The template will attempt to update-replace the permission set resource, which is set in the resource provider schema to "delete then create". It will attempt to delete the existing permission set, which will fail because there is an active assignment. The stack then goes into rollback, which then attempts to create the (failed-to-delete) permission set, which fails because the permission set already exists. This puts the stack in `UPDATE_ROLLBACK_FAILED`.
