### ISSUE TITLE
Getting an error while creating/updating stack

### ISSUE THREAD

**Issue by usulkies** [aws-cloudformation/aws-cloudformation-resource-providers-sso#8]
Hello,
I created a stack template file based on[ this example](https://github.com/hayao-k/aws-sso-cloudformation-sample/blob/master/sso-admin.yaml
).
The stack should create SSO resources:
1. Custom permissions set
2. Many assignments of this permission set to groups in accounts.
When creating the stack with a few assignments (on-two groups to one-two accounts) - it succeeds.
But when adding a few more assignments, to more than 2 accounts - the process fails for all assignments with the following error:
Unable to retrieve PermissionSetArn attribute for AWS::SSO::PermissionSet, with error message READ and LIST handlers must return synchronously.

This happens when either creating a stack from-scratch or when updating an existing stack to add some assignments only.

**Comment by allyman17** [comment]
@usulkies I'm glad to see i'm not the only one facing this issue. I think this error is being caused because to many resources are being created at once ( Just a guess), Whilst this isn't and ideal solution it defiantly got me around this issue. I added a DependsOn under each SSO::Assignment for the previous SSO::Assignment resource, like so 
```
# Account Assignment
  rAccoiunt1Group1AdministratorAccess:
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref pAwsSsoInsanceArn
      PermissionSetArn: !GetAtt rPermissionSetAdministratorAccess.PermissionSetArn
      PrincipalId: !FindInMap [ mGroups, Group1, Id ]
      PrincipalType: 'GROUP'
      TargetId: !FindInMap [ mAccounts, Account1, Id ]
      TargetType: 'AWS_ACCOUNT'

  rAccount2Group1ViewOnlyAccess:
    DependsOn: rAccoiunt1Group1AdministratorAccess
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref pAwsSsoInsanceArn
      PermissionSetArn: !GetAtt rPermissionSetViewOnlyAccess.PermissionSetArn
      PrincipalId: !FindInMap [ mGroups, Group1, Id ]
      PrincipalType: 'GROUP'
      TargetId: !FindInMap [ mAccounts, Account2, Id ]
      TargetType: 'AWS_ACCOUNT'

  rAccount3User1AdministratorAccess:
    DependsOn: rAccount2Group1ViewOnlyAccess
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref pAwsSsoInsanceArn
      PermissionSetArn: !GetAtt rPermissionSetAdministratorAccess.PermissionSetArn
      PrincipalId: !FindInMap [ mUsers, User1, Id ]
      PrincipalType: USER'
      TargetId: !FindInMap [ mAccounts, Account3, Id ]
      TargetType: 'AWS_ACCOUNT'

  rAccount1Group2SecurityAudit:
    DependsOn: rAccount3User1AdministratorAccess
    Type: AWS::SSO::Assignment
    Properties: 
      InstanceArn: !Ref pAwsSsoInsanceArn
      PermissionSetArn: !GetAtt rPermissionSetSecurityAudit.PermissionSetArn
      PrincipalId: !FindInMap [ mGroups, Group2, Id ]
      PrincipalType: 'GROUP'
      TargetId: !FindInMap [ mAccounts, Account1, Id ]
      TargetType: 'AWS_ACCOUNT'
```
